version: '3'
services:
  db:
    image: postgres
    container_name: postgres_sqlalchemy_server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"